name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    paths-ignore:
      - "doc/*.rst"
  schedule:
    - cron: "17 3 * * 0"

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Main Script
        run: |
          pip install .
          pip install pytest
          pytest
